apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    dashboard:
      enabled: true
      insecure: true
    ports:
      http:
        exposedPort: 8888 
      https:
        exposedPort: 8443
