apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: cilium-pool
spec:
  blocks:
    - start: "10.14.0.230"
      stop: "10.14.0.240"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: cilium-l2adv
spec:
  interfaces:
    - eno1
  externalIPs: true
  loadBalancerIPs: true
