apiVersion: v1
kind: Namespace
metadata:
  name: kube-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cilium-helm
  namespace: kube-system
spec:
  interval: 1h
  url: https://helm.cilium.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium-release
  namespace: kube-system
spec:
  targetNamespace: kube-system
  interval: 10m
  timeout: 10m
  chart:
    spec:
      chart: cilium
      version: "1.17.x"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cilium-helm
  values:
    k8sServiceHost: "10.14.0.22" # TODO: confirm eva01 IP
    k8sServicePort: "6443"

    kubeProxyReplacement: true
    kubeProxyReplacementHealthzBindAddr: "0.0.0.0:10256"

    # k3s-specific CNI paths (required)
    cni:
      confFileMountPath: /var/lib/rancher/k3s/agent/etc/cni/net.d
      binPath: /var/lib/rancher/k3s/data/cni

    l2announcements:
      enable: true

    MTU: 1450

    ipam:
      mode: cluster-pool
      operator:
        clusterPoolIPv4PodCIDRList:
          - "10.42.0.0/16"
        clusterPoolIPv4MaskSize: 24

    tunnelProtocol: vxlan

    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
    bpf:
      masquerade: true
      hostLegacyRouting: true

    operator:
      replicas: 1
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"

    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
