apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-pvc
  namespace: clickhouse 
  labels:
    app: clickhouse-pvc
spec:
  storageClassName: nfs-k8s-keep
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
