apiVersion: v1
kind: Namespace
metadata:
  name: cronjobs
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: meal-notifier 
  namespace: cronjobs 
spec:
  schedule: "0 7 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: meal-notifier
            image: rorix/meal-notifier:latest
            env:
            - name: TELEGRAM_CHAT_ID
              valueFrom:
                secretKeyRef:
                  name: meal-secrets
                  key: TELEGRAM_CHAT_ID
            - name: TELEGRAM_HOMELAB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: meal-secrets
                  key: TELEGRAM_HOMELAB_TOKEN
            - name: BASE_URL
              valueFrom:
                secretKeyRef:
                  name: meal-secrets
                  key: BASE_URL
          restartPolicy: OnFailure
