apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: td-secret
  namespace: td
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store-apps
  refreshPolicy: Periodic
  refreshInterval: 10m
  dataFrom:
    - extract:
        key: apps/td
  target:
    name: td-secret
    creationPolicy: Owner
    deletionPolicy: Delete
