apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: searxng-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store-apps
  refreshPolicy: Periodic
  refreshInterval: 10m
  dataFrom:
    - extract:
        key: apps/searxng
  target:
    name: searxng-secret
    creationPolicy: Owner
    deletionPolicy: Delete
