apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-secrets
  namespace: oauth2-proxy
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store-apps
  refreshPolicy: Periodic
  refreshInterval: 10m
  dataFrom:
    - extract:
        key: apps/oauth2-proxy
  target:
    name: oauth2-proxy-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
