apiVersion: v1
kind: ConfigMap
metadata:
  name: victoriametrics-cm-static
  namespace: metrics
data:
  prometheus.yml: |
    scrape_configs:
    - job_name: eva01
      static_configs:
      - targets:
        - 192.168.1.22:9100
    - job_name: eva02
      static_configs:
      - targets:
        - 192.168.1.2:9100
    - job_name: eva03
      static_configs:
      - targets:
        - 192.168.1.23:9100
    - job_name: eva04
      static_configs:
      - targets:
        - 192.168.1.193:9100
    - job_name: cloudflared
      static_configs:
      - targets:
        - cloudflared-svc.cloudflared
    - job_name: victorialogs
      static_configs:
      - targets:
        - victorialogs-svc.logs:9428
    - job_name: twitch-bot
      static_configs:
      - targets:
        - twitch-svc.bots:80
    - job_name: 'blackbox-http'
      metrics_path: /probe
      params:
        module: [http]
      static_configs:
        - targets:
          - https://grafana.mvaldes.dev
          - https://about.mvaldes.dev
          - https://mvaldes.dev
          - https://umami.mvaldes.dev
          - https://vault.mvaldes.dev
          - https://docs.mvaldes.dev
          - https://db.mvaldes.dev
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: blackbox-svc.telemetry.svc.cluster.local:9115
    - job_name: 'blackbox-icmp'
      metrics_path: /probe
      params:
        module: [icmp]
      static_configs:
        - targets:
          - 192.168.1.2
          - 192.168.1.22
          - 192.168.1.13
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: blackbox-svc.telemetry.svc.cluster.local:9115
