apiVersion: v1
kind: PersistentVolume
metadata:
  name: victoriametrics
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: victoriametrics-pvc
    namespace: metrics
  csi:
    driver: nfs.csi.k8s.io
    volumeAttributes:
      csi.storage.k8s.io/pv/name: victoriametrics
      csi.storage.k8s.io/pvc/name: victoriametrics-pvc
      csi.storage.k8s.io/pvc/namespace: metrics
      server: 10.14.0.21
      share: /share/k8s/victoriametrics
      storage.kubernetes.io/csiProvisionerIdentity: 1757349754008-3337-nfs.csi.k8s.io
    volumeHandle: 10.14.0.21#share/k8s/victoriametrics##
  mountOptions:
    - soft
    - nfsvers=3
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-k8s-keep
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: victoriametrics-pvc
  namespace: metrics
  labels:
    app: victoriametrics-pvc
spec:
  storageClassName: nfs-k8s-keep
  volumeName: victoriametrics
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
