apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postiz-pvc
  namespace: postiz 
  labels:
    app: postiz-pvc
spec:
  storageClassName: nfs-k8s-keep
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
