apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    app: blog
spec:
  selector:
    matchLabels:
      app: blog
  replicas: 1
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: docker.io/rorix/blog:20261005-134531@sha256:f1c3c4313bbff3b8b9576b1899563948617c67bc91d8665eb17ba4ca94f4f45f # {"$imagepolicy" : "flux-system:blog-policy"}
        imagePullPolicy:
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort: 80
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: about
  labels:
    app: about
spec:
  selector:
    matchLabels:
      app: about
  replicas: 1
  template:
    metadata:
      labels:
        app: about
    spec:
      containers:
      - name: about
        image: rorix/about:latest
        imagePullPolicy:
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort: 80
      restartPolicy: Always
