apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-flux 
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: homelab-repository
  path: "./overlays/grafana"
  prune: true
  timeout: 1m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
