apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: discord 
  namespace: flux-system 
spec:
  providerRef:
    name: discord 
  eventMetadata:
    summary: "Cluster Event occured"
    cluster: "homelab"
  eventSeverity: info 
  eventSources:
    - kind: HelmRepository
      name: '*'
    - kind: HelmRelease
      name: '*'
    - kind: Kustomization 
      name: '*'
    - kind: GitRepository 
      name: '*'
    - kind: ImageUpdateAutomation
      name: '*'
    - kind: ImageRepository
      name: '*'
