apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gotify-secrets
  namespace: gotify
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store-apps
  refreshPolicy: Periodic
  refreshInterval: 10m
  dataFrom:
    - extract:
        key: apps/gotify
  target:
    name: gotify-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
