apiVersion: v1
kind: PersistentVolume
metadata:
  name: gotify
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: gotify-pvc
    namespace: gotify
  csi:
    driver: nfs.csi.k8s.io
    volumeAttributes:
      csi.storage.k8s.io/pv/name: gotify
      csi.storage.k8s.io/pvc/name: gotify-pvc
      csi.storage.k8s.io/pvc/namespace: gotify
      server: 10.14.0.21
      share: /share/k8s/gotify
      storage.kubernetes.io/csiProvisionerIdentity: 1757349754008-3337-nfs.csi.k8s.io
    volumeHandle: 10.14.0.21#share/k8s/gotify##
  mountOptions:
    - soft
    - nfsvers=3
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-k8s-keep
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gotify-pvc
  namespace: gotify
spec:
  storageClassName: nfs-k8s-keep
  volumeName: gotify
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
