apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak-ingressroute
  namespace: keycloak
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`keycloak.local.net`)
      services:
        - name: keycloak-svc
          port: 8080
