apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak-ingressroute
  namespace: keycloak
spec:
  entryPoints:
    - websecure
  tls: {}
  routes:
    - kind: Rule
      match: Host(`keycloak.int.mvaldes.dev`)
      services:
        - name: keycloak-svc
          port: 8080
