apiVersion: v1
kind: Namespace
metadata:
  name: telemetry
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-cm 
  namespace: telemetry
data:
  config.yml: |
    modules:
      icmp:
        prober: icmp
        timeout: 10s
        icmp:
          preferred_ip_protocol: "ip4" # or "ip6" or leave blank for auto
      
      http:
        prober: http
        timeout: 10s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
          valid_status_codes: [200]
          follow_redirects: true
          preferred_ip_protocol: "ip4"
