apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-media-pvc
  namespace: paperless
spec:
  storageClassName: nfs-k8s-keep
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data-pvc
  namespace: paperless
spec:
  storageClassName: nfs-k8s-keep
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
