apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: bot-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: bot-repository
  digestReflectionPolicy: IfNotPresent
  policy:
    alphabetical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: blog-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: blog-repository
  digestReflectionPolicy: IfNotPresent
  policy:
    alphabetical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: td-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: td-repository
  digestReflectionPolicy: IfNotPresent
  filterTags:
    pattern: '^[0-9]{8}-[0-9]{6}$'
  policy:
    alphabetical:
      order: desc
