apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo-deploy
  namespace: forgejo
  labels:
    app: forgejo
spec:
  selector:
    matchLabels:
      app: forgejo
  replicas: 1
  template:
    metadata:
      labels:
        app: forgejo
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: forgejo-pod
          image: codeberg.org/forgejo/forgejo:16
          imagePullPolicy: IfNotPresent
          env:
            - name: USER_UID
              value: "1000"
            - name: USER_GID
              value: "1000"
            - name: FORGEJO__database__DB_TYPE
              value: postgres
            - name: FORGEJO__database__HOST
              value: homelab-db-rw.db.svc.cluster.local:5432
            - name: FORGEJO__database__NAME
              value: git
            - name: FORGEJO__database__USER
              valueFrom:
                secretKeyRef:
                  name: forgejo-secrets
                  key: DB_USER
            - name: FORGEJO__database__PASSWD
              valueFrom:
                secretKeyRef:
                  name: forgejo-secrets
                  key: DB_PASSWD
          ports:
            - containerPort: 3000
              name: http
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: forgejo-data
      restartPolicy: Always
