apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-secrets
  namespace: forgejo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store-apps
  refreshPolicy: Periodic
  refreshInterval: 10m
  dataFrom:
    - extract:
        key: apps/forgejo
  target:
    name: forgejo-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner-secrets
  namespace: forgejo 
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store-apps
  refreshPolicy: Periodic
  refreshInterval: 10m
  dataFrom:
    - extract:
        key: apps/forgejo-runner
  target:
    name: forgejo-runner-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
