apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-secrets
  namespace: forgejo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store-apps
  refreshPolicy: Periodic
  refreshInterval: 10m
  dataFrom:
    - extract:
        key: apps/forgejo
  target:
    name: forgejo-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner-secrets
  namespace: forgejo 
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store-apps
  refreshPolicy: Periodic
  refreshInterval: 10m
  dataFrom:
    - extract:
        key: apps/forgejo-runner      # Vault path holding the runner token (+ uuid if you store it)
  target:
    name: forgejo-runner-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        config.yaml: |
          log:
            level: info
          server:
            connections:
              forgejo:
                url: https://git.int.mvaldes.dev/
                uuid: "{{ .uuid }}"
                token: "{{ .token }}"
          runner:
            file: /data/.runner
            capacity: 2
            timeout: 1h
            shutdown_timeout: 3h
            insecure: false
            fetch_timeout: 5s
            fetch_interval: 2s
            labels:
              - docker:host
          cache:
            enabled: true
            dir: /data/cache
            host: ""
            port: 0
          container:
            docker_host: "-"
            privileged: false
            valid_volumes: []
          host:
            workdir_parent: /data/workdir
