apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-secrets
  namespace: forgejo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store-apps
  refreshPolicy: Periodic
  refreshInterval: 10m
  dataFrom:
    - extract:
        key: apps/forgejo
  target:
    name: forgejo-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner-secrets
  namespace: forgejo 
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store-apps
  refreshPolicy: Periodic
  refreshInterval: 10m
  dataFrom:
    - extract:
        key: apps/forgejo-runner
  target:
    name: forgejo-runner-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        config.yaml: |
          log:
            level: info
          server:
            connections:
              forgejo:
                url: http://forgejo-svc
                uuid: "{{ .uuid }}"
                token: "{{ .token }}"
          runner:
            file: /data/.runner
            capacity: 2
            timeout: 1h
            shutdown_timeout: 3h
            insecure: false
            fetch_timeout: 5s
            fetch_interval: 2s
            labels:
              - docker:docker://catthehacker/ubuntu:act-latest
          cache:
            enabled: false
          container:
            network: bridge
            privileged: false
            force_pull: true
            valid_volumes: []
          host:
            workdir_parent: /data/workdir
