apiVersion: v1
kind: Service
metadata:
  name: forgejo-svc
  namespace: forgejo
spec:
  selector:
    app: forgejo
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: buildkitd
  namespace: forgejo
spec:
  selector: { app: buildkitd }
  ports:
    - { port: 1234, targetPort: 1234 }
