apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: searxng-pvc
  namespace: search
spec:
  storageClassName: nfs-k8s-keep
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
