apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: grafana-grafana-release
    namespace: grafana
  csi:
    driver: nfs.csi.k8s.io
    volumeAttributes:
      csi.storage.k8s.io/pv/name: grafana
      csi.storage.k8s.io/pvc/name: grafana-grafana-release
      csi.storage.k8s.io/pvc/namespace: grafana
      server: 10.14.0.21
      share: /share/k8s
      subdir: grafana
      storage.kubernetes.io/csiProvisionerIdentity: 1757349754008-3337-nfs.csi.k8s.io
    volumeHandle: 10.14.0.21#share/k8s#grafana##
  mountOptions:
    - soft
    - nfsvers=3
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-k8s-keep
  volumeMode: Filesystem
