apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-secrets
  namespace: keycloak
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store-apps
  refreshPolicy: Periodic
  refreshInterval: 10m
  dataFrom:
    - extract:
        key: apps/cert-manager
  target:
    name: cert-manager-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
