apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-pvc
  namespace: authentik
  labels:
    app: authentik-pvc
spec:
  storageClassName: nfs-k8s-keep
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
