apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-source-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store-core
  refreshPolicy: Periodic
  refreshInterval: 10m
  dataFrom:
    - extract:
        key: core/github
  target:
    name: github-source-secret
    creationPolicy: Owner
    deletionPolicy: Retain
