apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: bot-policy 
  namespace: flux-system 
spec:
  imageRepositoryRef:
    name: bot-repository 
  digestReflectionPolicy: IfNotPresent
  policy:
    alphabetical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: blog-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: blog-repository
  digestReflectionPolicy: IfNotPresent
  policy:
    alphabetical:
      order: asc
