apiVersion: v1
kind: ConfigMap
metadata:
  name: signoz-k8s-cm
  namespace: signoz
data:
  values.yaml: |
    global:
      imageRegistry: null
      imagePullSecrets: []
      storageClass: null
      clusterDomain: cluster.local
      clusterName: "homelab"
      deploymentEnvironment: "homelab"
      cloud: other
    nameOverride: ""
    fullnameOverride: ""
    enabled: true
    clusterName: ""
    otelCollectorEndpoint: signoz-signoz-helm-otel-collector.signoz.svc.cluster.local
    otelInsecure: true
    insecureSkipVerify: false
    signozApiKey: ""
    apiKeyExistingSecretName: ""
    apiKeyExistingSecretKey: ""
    otelTlsSecrets:
      enabled: false
    namespace: "signoz"
    presets:
      debugExporter:
        enabled: false
      otlpExporter:
        enabled: false
      otlphttpExporter:
        enabled: false
      selfTelemetry:
        enabled: false
      logsCollection:
        enabled: true
      hostMetrics:
        enabled: true
      kubeletMetrics:
        enabled: true
      kubernetesAttributes:
        enabled: true
      clusterMetrics:
        enabled: false
      prometheus:
        enabled: false
      resourceDetection:
        enabled: true
      k8sEvents:
        enabled: false
    otelAgent:
      enabled: true
      name: "otel-agent"
      image:
        registry: docker.io
        repository: signoz/signoz-otel-collector
        tag: v0.144.5
        pullPolicy: IfNotPresent
      imagePullSecrets: []
      command:
        name: /signoz-otel-collector
      configMap:
        create: true
      service:
        annotations: {}
        type: ClusterIP
        internalTrafficPolicy: Local
      serviceAccount:
        create: true
        annotations: {}
        name:
      annotations: {}
      podAnnotations: {}
      additionalEnvs: {}
      minReadySeconds: 5
      clusterRole:
        create: true
        annotations: {}
        name: ""
        rules:
          # k8sattributes processor requires these permissions
          - apiGroups: [""]
            resources: ["pods", "namespaces", "nodes", "persistentvolumeclaims"]
            verbs: ["get", "list", "watch"]
          - apiGroups: ["apps"]
            resources: ["replicasets"]
            verbs: ["get", "list", "watch"]
          - apiGroups: ["extensions"]
            resources: ["replicasets"]
            verbs: ["get", "list", "watch"]
          # other processors and receivers require these permissions
          - apiGroups: [""]
            resources: ["nodes", "endpoints"]
            verbs: ["list", "watch"]
          - apiGroups: ["batch"]
            resources: ["jobs"]
            verbs: ["list", "watch"]
          - apiGroups: [""]
            resources: ["nodes/proxy"]
            verbs: ["get"]
          - apiGroups: [""]
            resources: ["nodes/stats", "configmaps", "events"]
            verbs: ["create", "get"]
          - apiGroups: [""]
            resources: ["configmaps"]
            resourceNames: ["otel-container-insight-clusterleader"]
            verbs: ["get", "update"]
        clusterRoleBinding:
          annotations: {}
          name: ""
      ports:
        otlp:
          enabled: true
          containerPort: 4317
          servicePort: 4317
          nodePort: ""
          hostPort: 4317
          protocol: TCP
        otlp-http:
          enabled: true
          containerPort: 4318
          servicePort: 4318
          nodePort: ""
          hostPort: 4318
          protocol: TCP
        zipkin:
          enabled: false
        metrics:
          enabled: true
          containerPort: 8888
          servicePort: 8888
          nodePort: ""
          hostPort: 8888
          protocol: TCP
        zpages:
          enabled: false
        health-check:
          enabled: true
          containerPort: 13133
          servicePort: 13133
          nodePort: ""
          hostPort: 13133
          protocol: TCP
        pprof:
          enabled: false
          containerPort: 1777
          servicePort: 1777
          nodePort: ""
          hostPort: 1777
          protocol: TCP
      hostNetwork: false
      livenessProbe:
        enabled: true
        port: 13133
        path: /
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 6
        successThreshold: 1
      readinessProbe:
        enabled: true
        port: 13133
        path: /
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 6
        successThreshold: 1
      ingress:
        enabled: false
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
      priorityClassName: ""
      nodeSelector: {}
      tolerations:
        - operator: Exists
      affinity: {}
      podSecurityContext: {}
        # fsGroup: 2000
      securityContext: {}
      config:
        exporters:
          otlphttp:
            endpoint: http://signoz-signoz-helm-otel-collector.signoz.svc.cluster.local:4318
        service:
          telemetry:
            logs:
              encoding: json
          pipelines:
            traces:
              exporters: [otlphttp]
            metrics:
              exporters: [otlphttp]
            logs:
              exporters: [otlphttp]
    otelDeployment:
      enabled: true
      image:
        registry: docker.io
        repository: signoz/signoz-otel-collector
        tag: v0.144.5
      command:
        name: /signoz-otel-collector
      config:
        receivers:
          k8s_cluster/meter:
            auth_type: serviceAccount
            # collection_interval: 1h
            allocatable_types_to_report: [cpu]
            node_conditions_to_report: []
            resource_attributes:
              container.runtime: { enabled: false }
              container.runtime.version: { enabled: false }
              k8s.container.status.last_terminated_reason: { enabled: false }
              k8s.kubelet.version: { enabled: false }
              k8s.pod.qos_class: { enabled: false }
              k8s.namespace.name: { enabled: false }
        processors:
          k8sattributes/meter:
            extract:
              metadata:
                - k8s.namespace.name
                - k8s.node.name
                - k8s.pod.name
              labels:
                - tag_name: signoz.io/workload
                  key: signoz.io/workload
                  from: node
            filter:
              namespace: signoz
            pod_association:
              - sources:
                  - from: resource_attribute
                    name: k8s.node.name
          transform/meter:
            error_mode: ignore
            metric_statements:
              - context: metric
                statements:
                  - set(name, "signoz.meter.cpu.node.allocatable.usage") where name == "k8s.node.allocatable_cpu"
          filter/meter:
            error_mode: ignore
            metrics:
              metric:
                - 'name != "signoz.meter.cpu.node.allocatable.usage"'
              datapoint:
                - 'resource.attributes["k8s.namespace.name"] != "signoz"'
                - 'resource.attributes["signoz.io/workload"] == nil'
          transform/cleanup:
            error_mode: ignore
            metric_statements:
              - context: resource
                statements:
                  - delete_key(attributes, "k8s.namespace.name")
          batch/meter:
            send_batch_size: 50000
            timeout: 5s
        exporters:
          signozclickhousemeter:
            dsn: tcp://admin:27ff0399-0d3a-4bd8-919d-17c2181e6fb9@signoz-signoz-helm-clickhouse:9000/signoz_meter
            sending_queue:
              enabled: false
            timeout: 45s
        service:
          pipelines:
            metrics/meter:
              receivers: [k8s_cluster/meter]
              processors: [k8sattributes/meter, transform/meter, filter/meter, transform/cleanup, batch/meter]
              exporters: [signozclickhousemeter]
          telemetry:
            logs:
              encoding: json
