apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: atlantis-release
spec:
  targetNamespace: atlantis
  chart:
    spec:
      chart: atlantis
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: atlantis-helm
      version: 6.15.0
  valuesFrom:
    - kind: ConfigMap
      name: atlantis-cm
  interval: 5m0s
