apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: atuin-ingressroute
  namespace: atuin
spec:
  entryPoints:
    - websecure
  tls:
    secretName: wildcard-int-tls
  routes:
    - kind: Rule
      match: Host(`atuin.int.mvaldes.dev`)
      services:
        - name: atuin-svc
          port: 80
