apiVersion: resources.signoz.io/v1alpha1
kind: ServiceAccount
metadata:
  name: serviceaccount-sample
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: signoz-operator
spec:
  objectTemplate:
    spec:
      name: automation
  providerConfigRef:
    name: prod
