apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: atuin
resources:
  - ../../base/nfs-pvc
  - ../../base/external-secret
  - ../../base/traefik-route
  - deployment.yaml
  - service.yaml
patches:
  - path: external-secrets.yaml
  - path: ingress.yaml
  - path: pvc.yaml
