apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: blog
  labels:
    app: blog
spec:
  selector:
    matchLabels:
      app: blog
  replicas: 1
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: docker.io/rorix/blog:20260511-194758@sha256:f0b5ce14120b971fc3e96e1da51f87f91550daa9e7401b612151776a4d8a37b5 # {"$imagepolicy" : "flux-system:blog-policy"}
        imagePullPolicy:
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort: 80
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: about
  namespace: blog
  labels:
    app: about
spec:
  selector:
    matchLabels:
      app: about
  replicas: 1
  template:
    metadata:
      labels:
        app: about
    spec:
      containers:
      - name: about
        image: rorix/about:latest
        imagePullPolicy:
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort: 80
      restartPolicy: Always
