apiVersion: v1
kind: Service
metadata:
  name: calibre-svc
  namespace: calibre
spec:
  selector:
    app: calibre-deploy
  type: ClusterIP
  ports:
  - name: calibre-svc
    protocol: TCP
    port: 8083
    targetPort: 8083
