apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2025.7.0
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config/config.yaml
            - run
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared/config
              readOnly: true
            - name: creds
              mountPath: /etc/cloudflared/creds/tunnel.json
              subPath: tunnel.json
              readOnly: true
            - name: cert
              mountPath: /etc/cloudflared/creds/cert.pem
              subPath: cert.pem
              readOnly: true
      volumes:
        - name: creds
          secret:
            secretName: cloudflared-secrets
            items:
              - key: tunnel.json
                path: tunnel.json
        - name: config
          configMap:
            name: cloudflared
            items:
              - key: config.yaml
                path: config.yaml
        - name: cert
          secret:
            secretName: cloudflared-secrets
            items:
              - key: cert.pem
                path: cert.pem
