apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-pvc
  namespace: vault
spec:
  storageClassName: nfs-k8s-keep
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
