apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vector-agent
  namespace: logs
  labels:
    app: vector-agent
spec:
  selector:
    matchLabels:
      app: vector-agent
  template:
    metadata:
      labels:
        app: vector-agent
    spec:
      serviceAccountName: vector
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      securityContext:
        fsGroup: 1000
      containers:
        - name: vector-agent
          image: timberio/vector:0.43.1-distroless-libc
          args:
            - --config-dir
            - /etc/vector/
          env:
            - name: VECTOR_LOG
              value: 'info'
            - name: VECTOR_SELF_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: VECTOR_SELF_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: VECTOR_SELF_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CLICLHOUSE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: vector-secret
                  key: username
            - name: CLICLHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vector-secret
                  key: password
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
            - name: k8s-logs
              mountPath: /var/log
              readOnly: true
            - name: config
              mountPath: /etc/vector
              readOnly: true
            - name: data
              mountPath: /vector-data-dir
      terminationGracePeriodSeconds: 30
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/America/Chicago
        - name: k8s-logs
          hostPath:
            path: /var/log
        - name: config
          projected:
            sources:
              - configMap:
                  name: vector-config
        - name: data
          hostPath:
            path: '/opt/vector'
