apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store-core
  refreshPolicy: Periodic
  refreshInterval: 10m
  dataFrom:
    - extract:
        key: core/db
  target:
    name: db-secret
    creationPolicy: Owner
    deletionPolicy: Delete
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-backup-creds
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store-core
  refreshPolicy: Periodic
  refreshInterval: 10m
  dataFrom:
    - extract:
        key: core/aws
  target:
    name: pg-backup-creds
    creationPolicy: Owner
    deletionPolicy: Delete
