apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: openai
spec:
  ai:
    provider:
      openai:
        model: {}
  policies:
    auth:
      secretRef:
        name: agentgateway-secrets
        key: OPENAI_KEY
---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: anthropic
spec:
  ai:
    provider:
      anthropic: {}
  policies:
    ai:
      routes:
        '/v1/messages': Messages
        '*': Passthrough
    auth:
      secretRef:
        name: agentgateway-secrets
        key: CLAUDE_KEY
---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: openrouter
spec:
  ai:
    provider:
      openai:
        model: {}
      host: openrouter.ai
      port: 443
      path: /api/v1/chat/completions
  policies:
    auth:
      secretRef:
        name: agentgateway-secrets
        key: OPENROUTER_KEY
    tls:
      sni: openrouter.ai


