apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: openai
spec:
  ai:
    provider:
      openai: {}
  policies:
    auth:
      secretRef:
        name: agentgateway-secrets
        key: OPENAI_KEY
---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: anthropic
spec:
  ai:
    provider:
      anthropic: {}
  policies:
    ai:
      routes:
        '/v1/messages': Messages
        '*': Passthrough
    auth:
      secretRef:
        name: agentgateway-secrets
        key: CLAUDE_KEY
---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: openrouter
spec:
  ai:
    provider:
      openai: {}
      host: openrouter.ai
      port: 443
      path: /api/v1/chat/completions
  policies:
    auth:
      secretRef:
        name: agentgateway-secrets
        key: OPENROUTER_KEY
    tls:
      sni: openrouter.ai


---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: mcp
spec:
  mcp:
    failureMode: FailOpen
    prefixMode: Conditional
    targets:
      - name: signoz
        static:
          host: signoz-mcp-server.signoz.svc.cluster.local
          port: 8000
          path: /mcp
          protocol: StreamableHTTP
      - name: grafana
        static:
          host: grafana-mcp-server.grafana.svc.cluster.local
          port: 8000
          path: /mcp
          protocol: StreamableHTTP
      - name: doit
        static:
          host: td-svc-mcp.td.svc.cluster.local
          port: 80
          path: /mcp
          protocol: StreamableHTTP
