apiVersion: v1
kind: PersistentVolume
metadata:
  name: garage-meta
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: garage-pvc-meta
    namespace: garage
  csi:
    driver: nfs.csi.k8s.io
    volumeAttributes:
      csi.storage.k8s.io/pv/name: garage-meta
      csi.storage.k8s.io/pvc/name: garage-pvc-meta
      csi.storage.k8s.io/pvc/namespace: garage
      server: 10.14.0.21
      share: /share/k8s
      subdir: garage-meta
      storage.kubernetes.io/csiProvisionerIdentity: 1757349754008-3337-nfs.csi.k8s.io
    volumeHandle: 10.14.0.21#share/k8s#garage-meta##
  mountOptions:
    - soft
    - nfsvers=3
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-k8s-keep
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-pvc-meta
  namespace: garage
  labels:
    app: garage-pvc-meta
spec:
  storageClassName: nfs-k8s-keep
  volumeName: garage-meta
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: garage-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: garage-pvc-data
    namespace: garage
  csi:
    driver: nfs.csi.k8s.io
    volumeAttributes:
      csi.storage.k8s.io/pv/name: garage-data
      csi.storage.k8s.io/pvc/name: garage-pvc-data
      csi.storage.k8s.io/pvc/namespace: garage
      server: 10.14.0.21
      share: /share/k8s
      subdir: garage-data
      storage.kubernetes.io/csiProvisionerIdentity: 1757349754008-3337-nfs.csi.k8s.io
    volumeHandle: 10.14.0.21#share/k8s#garage-data##
  mountOptions:
    - soft
    - nfsvers=3
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-k8s-keep
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-pvc-data
  namespace: garage
  labels:
    app: garage-pvc-data
spec:
  storageClassName: nfs-k8s-keep
  volumeName: garage-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
