apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-meta-pvc
  namespace: garage
spec:
  storageClassName: nfs-k8s-keep
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-data-pvc
  namespace: garage
spec:
  storageClassName: nfs-k8s-keep
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
