apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nocodb-secret
  namespace: nocodb 
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store-apps
  refreshPolicy: Periodic
  refreshInterval: 10m
  dataFrom:
    - extract:
        key: apps/nocodb
  target:
    name: nocodb-secret
    creationPolicy: Owner
    deletionPolicy: Delete
