apiVersion: v1
kind: PersistentVolume
metadata:
  name: nocodb
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: nocodb-pvc
    namespace: nocodb
  csi:
    driver: nfs.csi.k8s.io
    volumeAttributes:
      csi.storage.k8s.io/pv/name: nocodb
      csi.storage.k8s.io/pvc/name: nocodb-pvc
      csi.storage.k8s.io/pvc/namespace: nocodb
      server: 10.14.0.21
      share: /share/k8s/nocodb
      storage.kubernetes.io/csiProvisionerIdentity: 1757349754008-3337-nfs.csi.k8s.io
    volumeHandle: 10.14.0.21#share/k8s/nocodb##
  mountOptions:
    - soft
    - nfsvers=3
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-k8s-keep
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nocodb-pvc
  namespace: nocodb
spec:
  storageClassName: nfs-k8s-keep
  volumeName: nocodb
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
