apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: signoz-mcp-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store-apps
  refreshPolicy: Periodic
  refreshInterval: 10m
  dataFrom:
    - extract:
        key: apps/signoz-mcp
  target:
    name: signoz-mcp-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
