apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: signoz-helm
spec:
  targetNamespace: signoz
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: signoz
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: signoz-helm
      version: 0.139.0
  interval: 1m0s
  valuesFrom:
    - kind: ConfigMap
      name: signoz-cm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-helm
spec:
  targetNamespace: signoz
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: k8s-infra
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: signoz-helm
      version: 0.17.0
  interval: 1m0s
  valuesFrom:
    - kind: ConfigMap
      name: signoz-k8s-cm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: operator
spec:
  targetNamespace: signoz
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: signoz-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: signoz-helm
      version: 0.0.1
  interval: 1m0s
