apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: signoz
resources:
  - clickhouse-pv.yaml
  - ingress.yaml
  - mcp-server.yaml
  - otel-internal-monitor.yaml
  - signoz-config.yaml
  - signoz-k8s-config.yaml
  - signoz.yaml
