apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: signoz-clickhouse-data
  labels:
    app: signoz-clickhouse
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-direct
  volumeName: signoz-clickhouse-data-eva04
  resources:
    requests:
      storage: 50Gi
