apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gotify-webhook
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store-apps
  refreshPolicy: Periodic
  refreshInterval: 10m
  dataFrom:
    - extract:
        key: apps/gotify
  target:
    name: gotify-webhook
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      data:
        address: "{{ .GOTIFY_URL }}/message?token={{ .GOTIFY_FLUX_TOKEN }}"
