apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-helm
  namespace: prometheus 
spec:
  interval: 1m0s
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-release 
  namespace: prometheus 
spec:
  targetNamespace: prometheus 
  chart:
    spec:
      chart: prometheus 
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-helm
      version: 25.8.2
  interval: 1m0s
  valuesFrom:
    - kind: ConfigMap
      name: prometheus-cm 
