apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: redis-pvc
    namespace: db
  csi:
    driver: nfs.csi.k8s.io
    volumeAttributes:
      csi.storage.k8s.io/pv/name: redis
      csi.storage.k8s.io/pvc/name: redis-pvc
      csi.storage.k8s.io/pvc/namespace: db
      server: 10.14.0.21
      share: /share/k8s
      subdir: redis
      storage.kubernetes.io/csiProvisionerIdentity: 1757349754008-3337-nfs.csi.k8s.io
    volumeHandle: 10.14.0.21#share/k8s#redis##
  mountOptions:
    - soft
    - nfsvers=3
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-k8s
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: db
spec:
  storageClassName: nfs-k8s
  volumeName: redis
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
